"""oscal.py — Emit NIST OSCAL assessment-results from ControlStatus objects.

Produces a JSON-serialisable dict that conforms to the OSCAL assessment-results
model (https://pages.nist.gov/OSCAL/). Uses stdlib only (no new dependencies).

Supports:
  - One result entry per framework
  - reviewed-controls with all assessed controls
  - findings for FAIL controls with evidence links
  - Manual controls flagged with state "not-satisfied" (human evidence required)
"""

import uuid
from collections import defaultdict
from datetime import datetime, timezone

from audit_packs.models import AssessmentStatus, ControlStatus


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _uuid() -> str:
    return str(uuid.uuid4())


def to_assessment_results(control_statuses: list[ControlStatus]) -> dict:
    """Convert a list of ControlStatus objects to an OSCAL assessment-results dict.

    Returns a JSON-serialisable dict with the OSCAL top-level structure:
      {"assessment-results": {"uuid": ..., "metadata": ..., "results": [...]}}
    """
    if not control_statuses:
        return {
            "assessment-results": {
                "uuid": _uuid(),
                "metadata": _metadata(),
                "results": [],
            }
        }

    # Group by framework
    by_framework: dict[str, list[ControlStatus]] = defaultdict(list)
    for cs in control_statuses:
        by_framework[cs.framework].append(cs)

    results = []
    for framework, statuses in by_framework.items():
        results.append(_build_result(framework, statuses))

    return {
        "assessment-results": {
            "uuid": _uuid(),
            "metadata": _metadata(),
            "results": results,
        }
    }


def _metadata() -> dict:
    return {
        "title": "audit-packs SOC 2 / NIST 800-53 Assessment Results",
        "last-modified": _now_iso(),
        "version": "1.0",
        "oscal-version": "1.1.2",
        "remarks": (
            "Generated by audit-packs (https://github.com/prakharsingh/audit-packs). "
            "Code-observable controls are assessed automatically; controls marked "
            "assessment:manual require human evidence for SOC 2 attestation."
        ),
    }


def _build_result(framework: str, statuses: list[ControlStatus]) -> dict:
    findings = []
    control_selections: list[dict] = []

    # Separate by status to build both the reviewed-controls list and findings
    include_all = [{"control-id": s.control_id} for s in statuses]
    if include_all:
        control_selections.append({"include-controls": include_all})

    for cs in statuses:
        if cs.status == AssessmentStatus.FAIL:
            for cf in cs.findings:
                findings.append(
                    {
                        "uuid": _uuid(),
                        "title": f"[{cs.framework}] {cs.control_id} — {cs.control_title}",
                        "description": cf.finding.message,
                        "target": {
                            "type": "statement-id",
                            "target-id": cs.control_id,
                            "status": {
                                "state": "not-satisfied",
                                "reason": "fail",
                            },
                        },
                        "related-observations": [
                            {
                                "observation-uuid": _uuid(),
                                "description": (
                                    f"Engine: {cf.finding.engine} ({cf.finding.check_id}) "
                                    f"— {cf.finding.file}:{cf.finding.line}"
                                ),
                                "evidence": cf.finding.evidence,
                                "severity": cf.finding.severity,
                            }
                        ],
                    }
                )
        elif cs.status == AssessmentStatus.MANUAL:
            # Manual controls appear in findings with state "not-satisfied" and
            # a note that human evidence is required.
            findings.append(
                {
                    "uuid": _uuid(),
                    "title": f"[{cs.framework}] {cs.control_id} — {cs.control_title}",
                    "description": (
                        "This control requires manual attestation. "
                        "No automated checks are available for this criterion."
                    ),
                    "target": {
                        "type": "statement-id",
                        "target-id": cs.control_id,
                        "status": {
                            "state": "not-satisfied",
                            "reason": "manual-evidence-required",
                        },
                    },
                    "related-observations": [],
                }
            )

    return {
        "uuid": _uuid(),
        "title": framework,
        "description": f"Assessment results for {framework}",
        "reviewed-controls": {
            "control-selections": control_selections,
        },
        "findings": findings,
    }
