import html
import json
import os
import requests
from audit_packs_core.models import (
    ControlFinding,
    ControlStatus,
    AssessmentStatus,
    severity_rank,
)

# Status display helpers
_STATUS_ICON = {
    AssessmentStatus.PASS: "✅",
    AssessmentStatus.FAIL: "❌",
    AssessmentStatus.MANUAL: "📋",
    AssessmentStatus.NOT_APPLICABLE: "➖",
}

_SARIF_LEVEL = {
    "low": "note",
    "medium": "warning",
    "high": "error",
    "critical": "error",
}


def build_comments(scored_findings: list, commit_sha: str) -> list[dict]:
    """Build PR review comments for surfaced ScoredFindings."""
    comments = []
    for sf in scored_findings:
        if not sf.surfaced:
            continue
        result = sf.result
        cf = result.control_finding
        f = cf.finding
        comps = sf.components
        score_pct = round(sf.finding_score * 100)

        breakdown = (
            f"rule {round(comps.rule_confidence * 100)}% · "
            f"evidence {round(comps.evidence_confidence * 100)}% · "
            f"consensus {round(comps.model_consensus * 100)}% · "
            f"history {round(comps.historical_precision * 100)}% · "
            f"severity {round(comps.control_severity * 100)}% · "
            f"flow {round(comps.flow_confidence * 100)}%"
        )

        body = (
            f"**[{cf.framework.upper()} / {cf.control_id} — {cf.control_title}]**  score: {score_pct}%\n"
            f"- Severity: `{f.severity}`  |  Engine: `{f.engine}` (`{f.check_id}`)\n"
            f"- Finding: {f.message}\n"
            f"- Score breakdown: {breakdown}\n"
            f"Evidence: `{f.evidence}`\n"
            f"Rationale: {result.rationale}"
        )
        comments.append({"path": f.file, "line": f.line, "side": "RIGHT", "body": body})
    return comments


def build_summary_comment(all_scored: list, threshold: float, weights: dict) -> str:
    """Build the summary comment posted once after inline comments."""
    from collections import defaultdict

    by_framework: dict[str, list] = defaultdict(list)
    for sf in all_scored:
        fw = sf.result.control_finding.framework
        by_framework[fw].append(sf)

    lines = [
        "## Audit Packs Summary",
        "| Framework | Findings | Suppressed | Avg Score |",
        "|---|---|---|---|",
    ]
    total_surfaced = 0
    total_suppressed = 0

    for fw, sfs in sorted(by_framework.items()):
        surfaced = [s for s in sfs if s.surfaced]
        suppressed = [s for s in sfs if not s.surfaced]
        avg = (
            round(sum(s.finding_score for s in surfaced) / len(surfaced) * 100)
            if surfaced
            else 0
        )
        lines.append(f"| {fw} | {len(surfaced)} | {len(suppressed)} | {avg}% |")
        total_surfaced += len(surfaced)
        total_suppressed += len(suppressed)

    lines.append("")
    lines.append(
        f"Total: {total_surfaced} surfaced, {total_suppressed} suppressed (FP). "
        f"Threshold: {round(threshold * 100)}%."
    )
    weight_formula = " + ".join(
        f"{w}·{k}"
        for k, w in [
            ("rule", weights.get("rule", 0.20)),
            ("evidence", weights.get("evidence", 0.15)),
            ("consensus", weights.get("consensus", 0.25)),
            ("history", weights.get("history", 0.10)),
            ("severity", weights.get("severity", 0.10)),
            ("flow", weights.get("flow", 0.20)),
        ]
    )
    lines.append(f"Score = {weight_formula}")
    return "\n".join(lines)


def gate_failed(control_findings: list[ControlFinding], fail_on: str) -> bool:
    threshold = severity_rank(fail_on)
    return any(
        severity_rank(cf.finding.severity) >= threshold for cf in control_findings
    )


def build_coverage_matrix(
    control_statuses: list[ControlStatus],
    fmt: str = "md",
    *,
    title: str = "Audit Packs Control Coverage Matrix",
    description: str = (
        "Compliance control coverage report generated by audit-packs, "
        "including pass, fail, manual, and not-applicable assessment status."
    ),
    canonical_url: str = "",
) -> str:
    """Build a human-readable control coverage matrix.

    Args:
        control_statuses: Output of coverage.compute_coverage().
        fmt:              "md" for Markdown, "html" for a complete HTML document,
                          or "html-fragment" for an embeddable table.
        title:            HTML document title when fmt is "html".
        description:      HTML meta description when fmt is "html".
        canonical_url:    Optional canonical URL when fmt is "html".

    Returns:
        A string containing the formatted matrix.
    """
    if fmt == "html":
        return _coverage_html_document(
            control_statuses,
            title=title,
            description=description,
            canonical_url=canonical_url,
        )
    if fmt == "html-fragment":
        return _coverage_html_table(control_statuses)
    return _coverage_md(control_statuses)


def _coverage_md(statuses: list[ControlStatus]) -> str:
    lines = []
    # Group by framework
    frameworks: dict[str, list[ControlStatus]] = {}
    for s in statuses:
        frameworks.setdefault(s.framework, []).append(s)

    for fw, fw_statuses in frameworks.items():
        n_pass = sum(1 for s in fw_statuses if s.status == AssessmentStatus.PASS)
        n_fail = sum(1 for s in fw_statuses if s.status == AssessmentStatus.FAIL)
        n_manual = sum(1 for s in fw_statuses if s.status == AssessmentStatus.MANUAL)
        n_total = len(fw_statuses)

        lines.append(f"## {fw} — Control Coverage\n")
        lines.append(
            f"**Summary:** {n_pass} ✅ PASS · {n_fail} ❌ FAIL · "
            f"{n_manual} 📋 MANUAL · {n_total} total\n"
        )
        lines.append("| Control | Title | Status | Checks | Findings |")
        lines.append("|---------|-------|--------|--------|----------|")
        for s in fw_statuses:
            icon = _STATUS_ICON.get(s.status, "?")
            status_label = f"{icon} {s.status.value.upper()}"
            n_checks = len(s.check_ids)
            n_findings = len(s.findings)
            lines.append(
                f"| {s.control_id} | {s.control_title} | {status_label} "
                f"| {n_checks} | {n_findings} |"
            )
        lines.append("")

    return "\n".join(lines)


def _coverage_counts(statuses: list[ControlStatus]) -> dict[str, int]:
    return {
        "pass": sum(1 for s in statuses if s.status == AssessmentStatus.PASS),
        "fail": sum(1 for s in statuses if s.status == AssessmentStatus.FAIL),
        "manual": sum(1 for s in statuses if s.status == AssessmentStatus.MANUAL),
        "not_applicable": sum(
            1 for s in statuses if s.status == AssessmentStatus.NOT_APPLICABLE
        ),
        "total": len(statuses),
    }


def _coverage_html_table(statuses: list[ControlStatus]) -> str:
    rows = []
    for s in statuses:
        icon = _STATUS_ICON.get(s.status, "?")
        rows.append(
            f"<tr><td>{html.escape(s.control_id)}</td>"
            f"<td>{html.escape(s.control_title)}</td>"
            f"<td>{html.escape(icon)} {html.escape(s.status.value)}</td>"
            f"<td>{len(s.check_ids)}</td><td>{len(s.findings)}</td></tr>"
        )
    body = "\n".join(rows)
    return (
        "<table>\n"
        "<thead><tr><th>Control</th><th>Title</th><th>Status</th>"
        "<th>Checks</th><th>Findings</th></tr></thead>\n"
        f"<tbody>\n{body}\n</tbody>\n</table>"
    )


def _coverage_html_document(
    statuses: list[ControlStatus],
    *,
    title: str,
    description: str,
    canonical_url: str,
) -> str:
    counts = _coverage_counts(statuses)
    frameworks = sorted({s.framework for s in statuses})
    framework_label = ", ".join(frameworks) if frameworks else "No frameworks"
    title_text = title.strip() or "Audit Packs Control Coverage Matrix"
    description_text = description.strip() or (
        "Compliance control coverage report generated by audit-packs."
    )
    canonical = canonical_url.strip()
    table = _coverage_html_table(statuses)
    keywords = ", ".join(["compliance", "audit", "control coverage", *frameworks])
    schema = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": title_text,
        "description": description_text,
        "creator": {"@type": "SoftwareApplication", "name": "audit-packs"},
        "keywords": [
            "compliance",
            "audit",
            "control coverage",
            "security",
            *frameworks,
        ],
        "variableMeasured": [
            {"@type": "PropertyValue", "name": key, "value": value}
            for key, value in counts.items()
        ],
    }
    schema_json = json.dumps(schema, separators=(",", ":")).replace("</", "<\\/")

    canonical_tag = (
        f'  <link rel="canonical" href="{html.escape(canonical, quote=True)}">\n'
        if canonical
        else ""
    )
    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="utf-8">\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"  <title>{html.escape(title_text)}</title>\n"
        f'  <meta name="description" content="{html.escape(description_text, quote=True)}">\n'
        '  <meta name="robots" content="index,follow">\n'
        f'  <meta name="keywords" content="{html.escape(keywords, quote=True)}">\n'
        f'  <meta property="og:title" content="{html.escape(title_text, quote=True)}">\n'
        f'  <meta property="og:description" content="{html.escape(description_text, quote=True)}">\n'
        '  <meta property="og:type" content="website">\n'
        f'  <meta name="twitter:card" content="summary">\n'
        f'  <meta name="twitter:title" content="{html.escape(title_text, quote=True)}">\n'
        f'  <meta name="twitter:description" content="{html.escape(description_text, quote=True)}">\n'
        f"{canonical_tag}"
        f'  <script type="application/ld+json">{schema_json}</script>\n'
        "</head>\n"
        "<body>\n"
        f"  <main>\n"
        f"    <h1>{html.escape(title_text)}</h1>\n"
        f"    <p>{html.escape(description_text)}</p>\n"
        f"    <p>Frameworks: {html.escape(framework_label)}</p>\n"
        "    <dl>\n"
        f"      <dt>Pass</dt><dd>{counts['pass']}</dd>\n"
        f"      <dt>Fail</dt><dd>{counts['fail']}</dd>\n"
        f"      <dt>Manual</dt><dd>{counts['manual']}</dd>\n"
        f"      <dt>Not applicable</dt><dd>{counts['not_applicable']}</dd>\n"
        f"      <dt>Total</dt><dd>{counts['total']}</dd>\n"
        "    </dl>\n"
        f"{table}\n"
        "  </main>\n"
        "</body>\n"
        "</html>"
    )


def build_sarif(control_findings: list[ControlFinding]) -> dict:
    """Build an aggregate SARIF document from ControlFindings.

    Suitable for upload via actions/upload-sarif to GitHub code-scanning.
    """
    results = []
    rules: dict[str, dict] = {}

    for cf in control_findings:
        f = cf.finding
        rule_id = f.check_id
        if rule_id not in rules:
            rules[rule_id] = {
                "id": rule_id,
                "name": rule_id,
                "shortDescription": {"text": f.message},
                "properties": {
                    "compliance-control": f"{cf.framework}/{cf.control_id}",
                },
            }
        level = _SARIF_LEVEL.get(f.severity, "warning")
        results.append(
            {
                "ruleId": rule_id,
                "level": level,
                "message": {"text": f"{f.message} [{cf.framework}/{cf.control_id}]"},
                "locations": [
                    {
                        "physicalLocation": {
                            "artifactLocation": {
                                "uri": f.file,
                                "uriBaseId": "%SRCROOT%",
                            },
                            "region": {"startLine": f.line},
                        }
                    }
                ],
            }
        )

    return {
        "version": "2.1.0",
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "audit-packs",
                        "version": "1.0.0",
                        "informationUri": "https://github.com/prakharsingh/audit-packs",
                        "rules": list(rules.values()),
                    }
                },
                "results": results,
            }
        ],
    }


def write_job_summary(content: str) -> None:
    """Append *content* to the GitHub Actions job summary file."""
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return
    with open(summary_path, "a") as fh:
        fh.write(content)
        fh.write("\n")


def post_review(comments, summary, *, repo, pr_number, token, commit_sha) -> None:
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}/reviews"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    payload = {
        "commit_id": commit_sha,
        "body": summary,
        "event": "COMMENT",
        "comments": comments,
    }
    resp = requests.post(url, json=payload, headers=headers, timeout=30)
    resp.raise_for_status()


def post_slack_message(
    webhook_url: str, scored_findings: list, summary: str, is_failure: bool
) -> None:
    """Post summary and finding alerts to Slack webhook."""
    if not webhook_url:
        return

    # Guard against Slack's 3000-character limit for section text
    if len(summary) > 2900:
        summary = summary[:2850] + "\n\n... (summary truncated due to size limit)"

    color = "#FF0000" if is_failure else "#00FF00"
    emoji = "🚨" if is_failure else "✅"

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{emoji} Compliance Audit Scan Result",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"Status: *{'FAILED' if is_failure else 'PASSED'}*\n{summary}",
            },
        },
    ]

    surfaced = [sf for sf in scored_findings if sf.surfaced]
    if surfaced:
        blocks.append({"type": "divider"})
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Top Surfaced Compliance Findings ({len(surfaced)} total):*",
                },
            }
        )

        for sf in surfaced[:5]:
            cf = sf.result.control_finding
            f = cf.finding
            blocks.append(
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": (
                            f"• *[{cf.framework.upper()} / {cf.control_id}]* — *{cf.control_title}*\n"
                            f"  Severity: `{f.severity}` | Engine: `{f.engine}`\n"
                            f"  File: `{f.file}:{f.line}`\n"
                            f"  Finding: {f.message}\n"
                            f"  Evidence: `{f.evidence}`"
                        ),
                    },
                }
            )

        if len(surfaced) > 5:
            blocks.append(
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"And {len(surfaced) - 5} more findings... view OSCAL or HTML report for details.",
                        }
                    ],
                }
            )

    try:
        payload = {"attachments": [{"color": color, "blocks": blocks}]}
        resp = requests.post(webhook_url, json=payload, timeout=10)
        resp.raise_for_status()
    except Exception as e:
        import sys

        print(f"Warning: Failed to post Slack notification: {e}", file=sys.stderr)


def create_jira_issue(
    jira_url: str,
    jira_email: str,
    jira_api_token: str,
    jira_project: str,
    scored_findings: list,
    summary: str,
    control_statuses: list = None,
) -> None:
    """Create a Jira issue for compliance scan failure."""
    if not (jira_url and jira_email and jira_api_token and jira_project):
        return

    surfaced = [sf for sf in scored_findings if sf.surfaced]
    failed_controls = []
    if control_statuses:
        failed_controls = [
            cs for cs in control_statuses if cs.status == AssessmentStatus.FAIL
        ]

    if not surfaced and not failed_controls:
        return

    jira_url = jira_url.rstrip("/")
    api_url = f"{jira_url}/rest/api/3/issue"

    auth = (jira_email, jira_api_token)
    headers = {"Accept": "application/json", "Content-Type": "application/json"}

    if surfaced:
        description_text = (
            f"Compliance scan failed with {len(surfaced)} surfaced findings.\n\n"
            f"{summary}\n\n"
            "Failed Controls:\n"
        )
        for sf in surfaced:
            cf = sf.result.control_finding
            f = cf.finding
            description_text += (
                f"- [{cf.framework.upper()} / {cf.control_id}] {cf.control_title} ({f.severity})\n"
                f"  File: {f.file}:{f.line}\n"
                f"  Message: {f.message}\n"
                f"  Evidence: {f.evidence}\n\n"
            )
        issue_summary = f"Compliance Audit Failure: {len(surfaced)} findings detected"
    else:
        description_text = (
            f"Compliance scan failed with {len(failed_controls)} failed controls during full scan.\n\n"
            f"{summary}\n\n"
            "Failed Controls:\n"
        )
        for cs in failed_controls:
            description_text += (
                f"- [{cs.framework.upper()} / {cs.control_id}] {cs.control_title}\n"
            )
            for f in cs.findings[:5]:
                description_text += f"  • {f.finding.file}:{f.finding.line} — {f.finding.message} ({f.finding.severity})\n"
            if len(cs.findings) > 5:
                description_text += f"  • and {len(cs.findings) - 5} more findings...\n"
            description_text += "\n"
        issue_summary = (
            f"Compliance Audit Failure: {len(failed_controls)} controls failed"
        )

    payload = {
        "fields": {
            "project": {"key": jira_project},
            "summary": issue_summary,
            "description": {
                "type": "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": description_text}],
                    }
                ],
            },
            "issuetype": {"name": "Task"},
        }
    }

    try:
        resp = requests.post(
            api_url, json=payload, auth=auth, headers=headers, timeout=15
        )
        if resp.status_code == 201:
            issue_key = resp.json().get("key")
            print(f"::notice::Jira issue created successfully: {issue_key}")
        else:
            import sys

            print(
                f"Warning: Failed to create Jira issue. Response: {resp.text}",
                file=sys.stderr,
            )
    except Exception as e:
        import sys

        print(f"Warning: Failed to contact Jira API: {e}", file=sys.stderr)


def build_compact_coverage_summary(control_statuses: list[ControlStatus]) -> str:
    """Build a compact, notification-friendly summary of control coverage."""
    from collections import defaultdict

    by_fw = defaultdict(list)
    for s in control_statuses:
        by_fw[s.framework].append(s)

    lines = ["*Compliance Control Coverage:*"]
    for fw, fw_statuses in sorted(by_fw.items()):
        n_pass = sum(1 for s in fw_statuses if s.status == AssessmentStatus.PASS)
        n_fail = sum(1 for s in fw_statuses if s.status == AssessmentStatus.FAIL)
        n_manual = sum(1 for s in fw_statuses if s.status == AssessmentStatus.MANUAL)
        n_total = len(fw_statuses)
        lines.append(
            f"• *{fw.upper()}* — {n_pass} ✅ PASS · {n_fail} ❌ FAIL · {n_manual} 📋 MANUAL · {n_total} total"
        )
    return "\n".join(lines)
